 import { useState, useEffect, useRef } from 'react'
 import { supabase, isSupabaseConfigured } from './lib/supabase.js'
 import { FALLBACK_MENU as FM, FALLBACK_POSTS as FP, FALLBACK_HOURS as FH } from './lib/constants.js'
 import { GLOBAL_CSS } from './components/UI.jsx'
 import Header from './components/Header.jsx'
 import Footer from './components/Footer.jsx'
 import HomePage from './pages/HomePage.jsx'
 import { MenuPage, BlogPage, ContactPage } from './pages/PublicPages.jsx'
 import AdminDashboard from './pages/AdminDashboard.jsx'
 import PrivacyPolicy from './pages/PrivacyPolicy.jsx'

 export default function App() {
   const [page, setPage] = useState(() => {
       if (typeof window !== 'undefined' && window.location.hash === '#admin') {
             window.location.hash = ''
                   return 'admin'
                       }
                           return 'home'
                             })
                               const [posts, setPosts]         = useState(FP)
                                 const [menuItems, setMenuItems] = useState(FM)
                                   const [hoursData, setHoursData] = useState(FH)
                                     const pendingScroll = useRef(null)

                                       useEffect(() => {
                                           if (!isSupabaseConfigured()) return
                                               loadAll()
                                                 }, [])

                                                   const loadAll = async () => {
                                                       try {
                                                             const [{ data: postsData }, { data: menuData }, { data: hoursRaw }] = await Promise.all([
                                                                     supabase.from('blog_posts').select('*').order('created_at', { ascending: false }),
                                                                             supabase.from('menu_items').select('*').order('sort_order'),
                                                                                     supabase.from('business_hours').select('*'),
                                                                                           ])
                                                                                                 if (postsData?.length) setPosts(postsData)
                                                                                                       if (menuData?.length) {
                                                                                                               const grouped = menuData.reduce((acc, item) => {
                                                                                                                         const cat = item.category || 'Other'
                                                                                                                                   if (!acc[cat]) acc[cat] = []
                                                                                                                                             acc[cat].push(item)
                                                                                                                                                       return acc
                                                                                                                                                               }, {})
                                                                                                                                                                       setMenuItems(grouped)
                                                                                                                                                                             }
                                                                                                                                                                                   if (hoursRaw?.length) {
                                                                                                                                                                                           setHoursData({
                                                                                                                                                                                                     main: hoursRaw.filter(h => h.branch === 'main'),
                                                                                                                                                                                                               cbd:  hoursRaw.filter(h => h.branch === 'cbd'),
                                                                                                                                                                                                                       })
                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                 } catch (e) { console.warn('Supabase load error', e) }
                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                     useEffect(() => {
                                                                                                                                                                                                                                         if (page === 'home' && pendingScroll.current) {
                                                                                                                                                                                                                                               const target = pendingScroll.current
                                                                                                                                                                                                                                                     pendingScroll.current = null
                                                                                                                                                                                                                                                           requestAnimationFrame(() => requestAnimationFrame(() => {
                                                                                                                                                                                                                                                                   const el = document.getElementById(target)
                                                                                                                                                                                                                                                                           if (el) el.scrollIntoView({ behavior: 'smooth' })
                                                                                                                                                                                                                                                                                 }))
                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                       }, [page])

                                                                                                                                                                                                                                                                                         useEffect(() => {
                                                                                                                                                                                                                                                                                             const onHash = () => {
                                                                                                                                                                                                                                                                                                   if (window.location.hash === '#admin') {
                                                                                                                                                                                                                                                                                                           window.location.hash = ''
                                                                                                                                                                                                                                                                                                                   setPage('admin')
                                                                                                                                                                                                                                                                                                                           window.scrollTo(0, 0)
                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                         window.addEventListener('hashchange', onHash)
                                                                                                                                                                                                                                                                                                                                             return () => window.removeEventListener('hashchange', onHash)
                                                                                                                                                                                                                                                                                                                                               }, [])

                                                                                                                                                                                                                                                                                                                                                 const go = (id) => {
                                                                                                                                                                                                                                                                                                                                                     if (id === 'top') {
                                                                                                                                                                                                                                                                                                                                                           if (page !== 'home') setPage('home')
                                                                                                                                                                                                                                                                                                                                                                 window.scrollTo({ top: 0, behavior: 'smooth' })
                                                                                                                                                                                                                                                                                                                                                                       return
                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                               if (id === 'admin' || id === 'privacy') {
                                                                                                                                                                                                                                                                                                                                                                                     setPage(id)
                                                                                                                                                                                                                                                                                                                                                                                           window.scrollTo(0, 0)
                                                                                                                                                                                                                                                                                                                                                                                                 return
                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                         const sections = ['menu', 'blog', 'contact', 'about']
                                                                                                                                                                                                                                                                                                                                                                                                             if (sections.includes(id)) {
                                                                                                                                                                                                                                                                                                                                                                                                                   if (page === 'home') {
                                                                                                                                                                                                                                                                                                                                                                                                                           const el = document.getElementById(id)
                                                                                                                                                                                                                                                                                                                                                                                                                                   if (el) { el.scrollIntoView({ behavior: 'smooth' }); return }
                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                               pendingScroll.current = id
                                                                                                                                                                                                                                                                                                                                                                                                                                                     setPage('home')
                                                                                                                                                                                                                                                                                                                                                                                                                                                           return
                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   setPage(id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       window.scrollTo(0, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (page === 'privacy') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return <PrivacyPolicy onBack={() => { setPage('home'); window.scrollTo(0, 0) }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (page === 'admin') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <AdminDashboard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     onExit={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               loadAll()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         setPage('home')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   window.scrollTo(0, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   posts={posts}         setPosts={setPosts}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           menuItems={menuItems} setMenuItems={setMenuItems}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   hoursData={hoursData} setHoursData={setHoursData}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <style>{GLOBAL_CSS}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <Header go={go} hoursData={hoursData} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {page === 'home'    && <HomePage    posts={posts} menuItems={menuItems} go={go} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {page === 'menu'    && <MenuPage    menuItems={menuItems} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {page === 'blog'    && <BlogPage    posts={posts} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {page === 'contact' && <ContactPage hoursData={hoursData} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <Footer go={go} setPage={setPage} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }